version: '3'
services:
  flask:
    build: .
    image: crud-api-on-flask_back_flask
    env_file:
      - .env
    environment:
      DB_HOST: mongodb
    networks:
      - net_flask
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    networks:
      - net_flask
    ports:
      - 27017:27017

networks:
  net_flask:
